workflows:
  android-release:
    name: Build Android Release APK and AAB
    max_build_duration: 60

    environment:
      flutter: "3.27.1"
      xcode: latest

    scripts:
      - name: Clean
        script: flutter clean

      - name: Get dependencies
        script: flutter pub get

      - name: Build APK
        script: flutter build apk --release

      - name: Build AAB
        script: flutter build appbundle --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
